" Setup for pathogen
source /home/bee/.dotfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}', '/home/bee/.dotfiles/vim/bundle/{}')

syntax on
filetype plugin indent on
set nocompatible
set hidden

" Map lead key to space
nnoremap <SPACE> <Nop>
map <Space> <Leader>

" General settings
set fileformat=unix
set encoding=utf-8
set autoread
set showcmd
set relativenumber
set wrap
set linebreak
set autoindent
set breakindent
set number
set numberwidth=1
set tabstop=4
set softtabstop=0
set shiftwidth=2
set textwidth=79
set expandtab
set autoindent
set conceallevel=2
set splitbelow
set splitright

" Settings for Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

""The bottom method is better but I'm leving the top one in as an example
"map <leader>nt :call NerdTreeToggle()<CR>
map <leader>nt :NERDTreeToggle<CR>
"map <leader>w :AutoPairsShortcutFastWrap<CR>

set clipboard=unnamedplus

" Remap tab keys to perform buffer actions
nmap <leader>t :enew<cr>
" Move to the next buffer
nmap gt :bnext<CR>
" Move to the previous buffer
nmap gT :bprevious<CR>
" Close the current buffer and move to the previous one
nmap <leader>bq :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>

" Theme config
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=darkred guibg=red
colorscheme wal
set background=dark
let g:airline_powerline_fonts = 1
" let g:airline_theme='distinguished'
hi Normal 	guibg=none ctermbg=none
hi Statement 	guibg=none ctermbg=none
hi Title	guibg=none ctermbg=none
hi Todo		guibg=none ctermbg=none
hi Underlined	guibg=none ctermbg=none
hi ErrorMsg	guibg=none ctermbg=none
hi LineNr	guibg=none ctermbg=none

" Define matching whitespace
match ExtraWhitespace /\s\+$/

" Set indent guides as default
let g:indent_guides_enable_on_vim_startup = 1
let dart_style_guide = 2
let dart_format_on_save = 0

" Show flake8 in gutter
let g:flake8_show_in_gutter=1

" WordProcessor setup
func! WordProcessor()
    colorscheme wal
    " movement changes
    map <Down> gj
    map j gj
    map <Up> gk
    map k gk
    " formatting text
    setlocal textwidth=0
    setlocal noexpandtab
    setlocal wrap
    setlocal linebreak
    setlocal nonumber
    " spelling
    setlocal spell spelllang=en_us
    autocmd BufReadPost * call litecorrect#init()
                      \ | call pencil#init()
endfu
com! WP call WordProcessor()

"" Pluggin Configuration

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let python_highlight_all=1

let g:vim_markdown_folding_disabled = 1

let g:vim_jsx_pretty_colorful_config = 1

let g:user_emmet_leader_key='<leader>h'

" Rainbow parentheses settup
let g:rainbow_active = 1

let g:airline#extensions#tabline#enabled = 1

" Setup for vim-notes
filetype plugin on
let g:pencil#wrapModeDefault = 'soft'

autocmd BufNewFile,BufRead *.jbuilder setlocal syntax=ruby
autocmd BufRead,BufNewFile *.md call WordProcessor()
autocmd FileType gitcommit call WordProcessor()

function! NerdTreeToggle()
  exe 'NERDTree'
endfunction

