" Setup for pathogen
source /home/bee/.dotfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}', '/home/bee/.dotfiles/vim/bundle/{}')
syntax on
filetype plugin indent on
set nocompatible

" Setup for vim-notes
filetype plugin on
let g:pencil#wrapModeDefault = 'soft'

" Theme config 
colorscheme wal
set background=dark " Setting dark mode
let g:airline_powerline_fonts = 1 
" let g:airline_theme='distinguished'
hi Normal 	guibg=none ctermbg=none 
hi Statement 	guibg=none ctermbg=none 
hi Title	guibg=none ctermbg=none 
hi Todo		guibg=none ctermbg=none 
hi Underlined	guibg=none ctermbg=none 
hi ErrorMsg	guibg=none ctermbg=none 
hi LineNr	guibg=none ctermbg=none 

" Set indent guides as default
let g:indent_guides_enable_on_vim_startup = 1

" Show flake8 in gutter
let g:flake8_show_in_gutter=1 

" Set Utf-8 to default
set encoding=utf-8

set linebreak
set autoindent
set breakindent
set number
set numberwidth=1 

" WordProcessor setup
func! WordProcessor()
	" movement changes
	map <Down> gj
	map j gj
	map <Up> gk
	map k gk
	" formatting text
	setlocal formatoptions=1
	setlocal noexpandtab
	setlocal wrap
	setlocal linebreak 
	setlocal nonumber
	" spelling
	setlocal spell spelllang=en_us
	autocmd BufReadPost * call litecorrect#init()
		          \ | call pencil#init()
endfu
com! WP call WordProcessor()

" Settings for Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

au BufNewFile,BufRead *.py
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79
    \ set expandtab
    \ set autoindent
    \ set fileformat=unix
    \ autocmd BufWritePost *.py call flake8#Flake8()
